[package]
name = "pyreval"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "pyreval"
crate-type = ["cdylib"]

[dependencies]
cpython = "*"
phf = "0.10.1"